module Bamboo
  module Settings
    COLUMN_COUNT            =   11
    INITIAL_RECORD_LIMIT    =  100
    MAX_SEARCH_RESULTS      = 1000
    SEQUENCE_DISPLAY_LENGTH =   20
    DEFAULT_REGION_END      = 1000

    COLUMN_NAMES = %w[QNAME FLAG RNAME POS MAPQ CIGAR RNEXT PNEXT TLEN SEQ QUAL]

    WINDOW_WIDTH  = 800
    WINDOW_HEIGHT = 600
    WINDOW_TITLE  = "Bamboo - BAM File Viewer"
  end
end
